const ItemActionTypes = {
	TOGGLE_ITEM_ACTIVE: 'TOGGLE_ITEM_ACTIVE',
	ADD_NEW_ITEM: 'ADD_NEW_ITEM',
	ITEM_BY_ID: 'ITEM_BY_ID',
	DELETE_ITEM: 'DELETE_ITEM',
	UPDATE_VALUES: 'UPDATE_VALUES'
}

export default ItemActionTypes
