const ItemActionTypes = {
	TOGGLE_ITEM_ACTIVE: 'TOGGLE_ITEM_ACTIVE',
	ADD_NEW_ITEM: 'ADD_NEW_ITEM',
	ITEM_BY_ID: 'ITEM_BY_ID',
	DELETE_ITEM: 'DELETE_ITEM',
	UPDATE_INPUT_VALUE: 'UPDATE_INPUT_VALUE',
	UPDATE_QUANTITY_HISTORY: 'UPDATE_QUANTITY_HISTORY',
	UPDATE_PRICE_HISTORY: 'UPDATE_PRICE_HISTORY',
	UPDATE_ITEM_VALUES: 'UPDATE_ITEM_VALUES',
	SET_CURRENT_USER: 'SET_CURRENT_USER',
	// TESTING
	SET_ITEMS_PER_PAGE: 'SET_ITEMS_PER_PAGE'
}

export default ItemActionTypes
